#  <center> Numpy & Pandas

In [1]:
import pandas as pd

import numpy as np
from numpy.random import randn
np.random.seed(101)

### Exercise set 1


#### Ex. 1.1
Work out the shape of the resulting arrays before executing the following cells. <br>
(HINT: Length of the innermost list gives the size of the rightmost shape index.) <br>
* set the variable "a_rows" to the correct number of row, and
* set the variable "a_columns" to the correct number of columns.

In [2]:
## don't change the following line of code in any way
a = np.array( [[11,12,13], [21,22,23], [31,32,33], [41,42,43]] ) 
print(a)

[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]


Now create 2 variales called `a_rows` and `a_columns` and set their values to how many rows and columns array `a` has.

In [3]:
## Solution...


#### Ex. 1.2
Create an np.array called `b` and manually set the values what you expect the output of `a[2:-3:2]` would be.

In [4]:
a = np.arange(8)     

In [5]:
## Solution...


#### Ex. 1.3
Create a two-dimensional array called `m` to represent the following matrix,
$$
\mathbf{m} = \left\lbrack\begin{array}{ccc}
1 & 1 & 2\cr
3 & 5 & 8\cr
13 & 21 & 34\cr
55 & 89 & 144
\end{array}\right\rbrack
$$

Then change all the elements with values 21, 34, 89, and 144 in matrix `m` (i.e. bottom right corner elements) to 1001 by using a slice.

In [6]:
## Solution...


In [7]:
# Solution...

#### Ex. 1.4

Let $A$ be the two-dimensional array
$$
\mathbf{A} = \left\lbrack\begin{array}{ccc}
2 & 1 & 0\cr
-1 & 2 & 1\cr
0 & -1 & 2
\end{array}\right\rbrack
$$

In the following line, initilise the two dimensional array `A` propperly to match matrix A.

In [8]:
## Solution...


Implement and apply the function
$$
f(x) = x^3 + xe^x + 1
$$
to $A$. <br>


In [9]:
# Solution...


#### Ex. 1.5
Use `base` to check if array `q` is a copy of array `p`. <br>
Now, do the same for a simple indexed slice of `p` (e.g. `p[1:2,3:4]`).

In [10]:
p = np.array([[0, 1, 2],[3, 4, 5],[6, 7,8],[9, 10, 11]]) 
rows = [0,0,3,3]   # indices for rows
cols = [0,2,0,2]   # indices for columns
q=p[rows,cols]


In [11]:
# Solution...


#### Ex. 1.6
Explore other ways of generating random numbers. <br>
Below you will find an example for generating samples from a binomial distribution. <br>
What other distributions can you sample? <br>
Further documentation: https://numpy.org/doc/stable/reference/random/generator.html

In [12]:
s = np.random.binomial(5, 0.5, size=25)


#### Ex. 1.7
Here are some `timeit` experiments for you to try. Check which methods are faster?

In [13]:
# Accessing a 2d array
nd = np.arange(100).reshape((10,10))

# accessing element of 2d array
%timeit -n 10000000 -r 3 nd[5][5]
%timeit -n 10000000 -r 3 nd[5,5]

113 ns ± 0.558 ns per loop (mean ± std. dev. of 3 runs, 10000000 loops each)
55.1 ns ± 0.693 ns per loop (mean ± std. dev. of 3 runs, 10000000 loops each)


In [14]:
# Multiplying two vectors
x = np.arange(10E7)
%timeit -n 1 -r 10 x*x
%timeit -n 1 -r 10 x**2

138 ms ± 23.3 ms per loop (mean ± std. dev. of 10 runs, 1 loop each)
141 ms ± 21.7 ms per loop (mean ± std. dev. of 10 runs, 1 loop each)


In [15]:
# Comparing range functions and iterating in loops
# Note: some distributions may see overflow in range() example

size = int(1E6)

%timeit for x in range(size): x**2

%timeit for x in np.arange(size): x**2

%timeit np.arange(size)**2

214 ms ± 37.3 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
62.1 ms ± 5.18 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
2.71 ms ± 169 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


#### Ex. 1.8
The Taylor series expansion for the trigonometric function $\arctan(y)$ is :
$$\arctan ( y) \, = \,y - \frac{y^3}{3} + \frac{y^5}{5}  - \frac{y^7}{7}  + \dots $$
Now, $\arctan(1) = \pi/4 $, so
$$ \pi = 4 \, \Big( 1- \frac{1}{3} + \frac{1}{5} - \frac{1}{7} + ... \Big) $$
<br>
We can represent the first few terms of the series expansion of $\arctan(y)$ using a numpy `Polynomial`, with coefficients:
$$0, +1, 0, -1/3, 0, +1/5, 0, -1/7,\ldots\,$$ 
and then use it to approximate $\pi$.

Write a function called `arctan` using the expansion above and use it to calculate an approximation of $\pi$ using numpy polynomials.

In [16]:
## You should use numpy.polynmial in your function so lets import it
from numpy.polynomial import Polynomial

In [17]:
## Solution...


### Exercise set 2

The first step in most data analytics projects is reading the data file. In this exercise, you'll create `Series` and `DataFrame` objects, both by hand and by reading data files.

#### Ex. 2.1

In the _Solution_ cell below, create a `DataFrame` fruits that looks like this:

![](https://i.imgur.com/Ax3pp2A.png)

In [18]:
# Solution


#### Ex 2.2

Create a variable `ingredients` with a Series that looks like:

```
Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Dinner, dtype: object
```

In [19]:
# Solution:


#### Ex 2.3
In the cell below, write code to save this `DataFrame` to disk as a csv file with the name `cows_and_goats.csv`.

In [20]:
animals = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
animals

Cows  Goats
Year 1    12     22
Year 2    20     19

In [21]:
### Solution


### Exercise set 3

#### Ex 3.1
 Read inputs/core_data.csv as a dataframe call it `cr` 
 
 ** show the head of it

In [22]:
### Solution


In [23]:
### Solution


#### Ex 3.2
 Use the .info() method to find out how many entries there are.

In [24]:
### Solution


#### Ex 3.3
What is the average `Depth CSF-A (m)` ?

In [25]:
### Solution


#### Ex 3.4
 What is the highest amount of `Reflectance a*` in the dataset?

In [26]:
### Solution


#### Ex 3.5
What is the amount of `Reflectance L*` for the highest amount of `Reflectance a*`

In [27]:
### Solution


In [28]:
### Solution


#### Ex 3.6
what is the minimum `NGR total counts (cps)`'s Lithology type?

In [29]:
### Solution


In [30]:
### Solution


#### Ex 3.7
How many `Holes` has the `Lithology` type of `Marls`?

In [31]:
### Solution


#### Ex 3.8
What is the data type of the `Hole` column in the dataset?

In [32]:
### Solution


#### Ex 3.9

Create a variable `df` containing the `Depth CSF-A (m)` and `Lithology` columns of the first 100 records

Hint: you may use `loc` or `iloc`. When working on the answer this question and the several of the ones that follow, keep the following "gotcha" described in the lecture:



In [33]:
### Solution


In [34]:
### Solution


#### Ex 3.10
What is the number of data in `df` in which `Depth CSF-A (m)` is more than **10** and less than **25**  

In [35]:
### Solution


#### Ex 3.11
Calculate the number of missing, and duplicated values? What is the number of unique values for `df`

In [36]:
### Solution


In [37]:
### Solution


In [38]:
### Solution


### Exercise set 4
We are going to load a new data. Run the below cell

** If you have time, apply your solutions for the questions above on the new dataset

In [39]:
wi = pd.read_csv('inputs/winemag-data-130k-v2.csv')

#### Ex 4.1
There are only so many words you can use when describing a bottle of wine. Is a wine more likely to be "tropical" or "fruity"? Create a Series descriptor_counts counting how many times each of these two words appears in the description column in the dataset.

In [40]:
### Solution


#### Ex 4.2
Who are the most common wine reviewers in the dataset? Create a `Series` whose index is the `taster_twitter_handle` category from the dataset, and whose values count how many reviews each person wrote.

In [41]:
### Solution



In [42]:
### Solution


#### Ex 4.3
Create a dataframe top_oceania_wines containing all reviews with at least 95 points (out of 100) for wines from Australia or New Zealand.

In [43]:
### Solution




#### Ex 4.4
What are the minimum and maximum prices for each `variety` of wine? Create a `DataFrame` whose index is the `variety` category from the dataset and whose values are the `min` and `max` values thereof.

In [44]:
### Solution


In [45]:
### Solution


#### Ex 4.5
I'm an economical wine buyer. Which wine is the "best bargain"? Create a variable bargain_wine with the title of the wine with the highest points-to-price ratio in the dataset.



In [46]:
### Solution
